// <auto-generated />
namespace MedicalManagement.infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddmedicalEntityAbstractConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddmedicalEntityAbstractConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "202004281752237_AddmedicalEntityAbstractConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
